# Pytorch Tensor

In [1]:
import torch
import math

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.9542e-03, 2.1062e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [6]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [8]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.5062, 0.8469, 0.2588],
         [0.2707, 0.4115, 0.6839]],

        [[0.0703, 0.5105, 0.9451],
         [0.2359, 0.1979, 0.3327]]])


In [9]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [10]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


In [11]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [12]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [13]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [14]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.7220, 0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941, 0.3788]])
tensor([[1.4439, 1.6434, 0.5224, 1.4750],
        [1.6657, 1.6888, 0.5882, 0.7576]])


In [15]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 세번째와 두번째 차원이 a랑 동일하고, 첫번째 차원은 존재하지 않습니다.
print(b)

c = a * torch.rand(   3, 1) # 세번째 차원 = 1이고, 두번째 차원은 a랑 동일합니다.
print(c)

d = a * torch.rand(   1, 2) # 세번째 차원이 a랑 동일하고, 두번째 차원 = 1입니다.
print(d)

tensor([[[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]]])
tensor([[[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]]])
tensor([[[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]]])


In [16]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # 차원은 반드시 맨 뒤 원소부터 맨 앞 원소로 차례대로 맞춰야 합니다.

c = a * torch.rand(   2, 3) # 세번째와 두번째 차원 모두 서로 다릅니다.

d = a * torch.rand((0, ))   # 비어있는 tensor는 broadcast 할 수 없습니다.

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [17]:
# 공용 함수
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# 삼각 함수와 그 역함수들
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# 비트 연산
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# 비교 연산:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # 많은 비교 연산자들은 broadcasting을 지원합니다!
print(torch.eq(d, e)) # bool 자료형을 가진 tensor를 반환합니다.

# 차원 감소 연산:
print('\nReduction ops:')
print(torch.max(d))        # 단일 원소 tensor를 반환합니다.
print(torch.max(d).item()) # 반환한 tensor로부터 값을 추출합니다.
print(torch.mean(d))       # 평균
print(torch.std(d))        # 표준 편차
print(torch.prod(d))       # 모든 숫자의 곱
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # 중복되지 않은 값들을 걸러냅니다.

# 벡터와 선형 대수 연산
v1 = torch.tensor([1., 0., 0.])         # x축 단위 벡터
v2 = torch.tensor([0., 1., 0.])         # y축 단위 벡터
m1 = torch.rand(2, 2)                   # 무작위 행렬
m2 = torch.tensor([[3., 0.], [0., 3.]]) # 단위 행렬에 3을 곱한 결과

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # z축 단위 벡터의 음수값 (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # m1 행렬을 3번 곱한 결과
print(torch.svd(m3))       # 특이값 분해

Common functions:
tensor([[0.6881, 0.8008, 0.2010, 0.2648],
        [0.8928, 0.9773, 0.0365, 0.9614]])
tensor([[1., 1., -0., 1.],
        [1., -0., 1., 1.]])
tensor([[ 0.,  0., -1.,  0.],
        [ 0., -1.,  0.,  0.]])
tensor([[ 0.5000,  0.5000, -0.2010,  0.2648],
        [ 0.5000, -0.5000,  0.0365,  0.5000]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.6545, 0.4144],
        [0.0696, 0.4648]])
tensor([[1.9635, 1.2431],
        [0.2089, 1.3944]])
torch.return_types.svd(
U=tensor([[-0.9008, -0.4343],
        [-0.4343,  0.9008]]),
S=tensor([2.5365, 0.9770]),
V=tensor([[-0.7330, -0.6802],
        [-0.6802,  0.7330]]))


C:\Users\AutoML\AppData\Local\Temp\ipykernel_11208\3529175983.py:46: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Cross.cpp:67.)
  print(torch.cross(v2, v1)) # z축 단위 벡터의 음수값 (v1 x v2 == -v2 x v1)


In [18]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # 이 연산은 메모리에 새로운 tensor를 생성합니다.
print(a)              # a는 변하지 않습니다.

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # 밑줄에 주목하세요.
print(b)              # b가 변합니다.

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [19]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4491, 0.6265],
        [0.9411, 0.4922]])

After adding:
tensor([[1.4491, 1.6265],
        [1.9411, 1.4922]])
tensor([[1.4491, 1.6265],
        [1.9411, 1.4922]])
tensor([[0.4491, 0.6265],
        [0.9411, 0.4922]])

After multiplying
tensor([[0.2017, 0.3925],
        [0.8858, 0.2423]])
tensor([[0.2017, 0.3925],
        [0.8858, 0.2423]])


In [20]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # c의 값이 변경되었습니다.

assert c is d           # c와 d가 서로 단순히 같은 값을 가지는지가 아니라 같은 객체인지 테스트합니다.
assert id(c) == old_id  # 새로운 c는 이전 객체와 확실히 같은 객체입니다.

torch.rand(2, 2, out=c) # 다시 한번 생성해봅시다!
print(c)                # c의 값이 다시 바뀌었습니다.
assert id(c) == old_id  # 하지만 여전히 같은 객체네요!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.1829, 0.7278],
        [0.1016, 0.3259]])
tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]])


In [21]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [23]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(b)
print(a)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[  1., 561.],
        [  1.,   1.]])


In [24]:
a = torch.rand(2, 2, requires_grad=True) # autograd를 켭니다.
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.4460, 0.9289],
        [0.6293, 0.6264]], requires_grad=True)
tensor([[0.4460, 0.9289],
        [0.6293, 0.6264]], grad_fn=<CloneBackward0>)
tensor([[0.4460, 0.9289],
        [0.6293, 0.6264]])
tensor([[0.4460, 0.9289],
        [0.6293, 0.6264]], requires_grad=True)


In [25]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [26]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [27]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.4704, 0.6077],
        [0.4757, 0.5874]])


In [28]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [30]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cpu')
z = x + y

# 텐서의 Shape 다루기

In [31]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [34]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)
print(c.shape)

tensor([[[[[0.8068]]]]])
torch.Size([1, 1, 1, 1, 1])


In [40]:
a = torch.rand(1,20)
print(a,a.shape)

b = a.squeeze(0)
print(b.shape, b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

tensor([[0.2889, 0.6504, 0.2299, 0.3186, 0.5693, 0.2708, 0.2421, 0.3695, 0.0238,
         0.3039, 0.5577, 0.8109, 0.2091, 0.7922, 0.1296, 0.8304, 0.0950, 0.2097,
         0.1072, 0.8870]]) torch.Size([1, 20])
torch.Size([20]) tensor([0.2889, 0.6504, 0.2299, 0.3186, 0.5693, 0.2708, 0.2421, 0.3695, 0.0238,
        0.3039, 0.5577, 0.8109, 0.2091, 0.7922, 0.1296, 0.8304, 0.0950, 0.2097,
        0.1072, 0.8870])
torch.Size([2, 2])
torch.Size([2, 2])


In [41]:
a =     torch.ones(4, 3, 2)

c = a * torch.rand(   3, 1) # 3번째 차원 = 1, 2번째 차원은 다음 코드랑 동일합니다.
print(c)

tensor([[[0.3628, 0.3628],
         [0.4679, 0.4679],
         [0.4378, 0.4378]],

        [[0.3628, 0.3628],
         [0.4679, 0.4679],
         [0.4378, 0.4378]],

        [[0.3628, 0.3628],
         [0.4679, 0.4679],
         [0.4378, 0.4378]],

        [[0.3628, 0.3628],
         [0.4679, 0.4679],
         [0.4378, 0.4378]]])


In [49]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # a * b를 시도하는 것은 runtime error가 발생합니다.
c = b.unsqueeze(1)       # 끝에 새로운 차원을 추가해서 2차원 tensor로 바꿉니다.
print(c.shape)
print(a * c)             # broadcasting이 다시 작동합니다!


torch.Size([3, 1])
tensor([[[0.8959, 0.8959],
         [0.4908, 0.4908],
         [0.1875, 0.1875]],

        [[0.8959, 0.8959],
         [0.4908, 0.4908],
         [0.1875, 0.1875]],

        [[0.8959, 0.8959],
         [0.4908, 0.4908],
         [0.1875, 0.1875]],

        [[0.8959, 0.8959],
         [0.4908, 0.4908],
         [0.1875, 0.1875]]])


In [50]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [51]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# torch 모듈에 있는 메소드에 대해서도 호출할 수 있습니다.
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [52]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [53]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.2156, 0.6103, 0.3515],
        [0.9615, 0.8342, 0.6184]])
[[0.21556973 0.6102984  0.3515206 ]
 [0.9615434  0.83415765 0.6184336 ]]


In [54]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.21556973  0.6102984   0.3515206 ]
 [ 0.9615434  17.          0.6184336 ]]
